### ISSUE TITLE
new Message

### ISSUE THREAD

**Issue by saulofr** [icanos/ng2-mqtt#1] opened 2016-10-05 13:16 UTC
Hi, I can't create a new message to send.

let mqtt_message = new Paho.MQTT.Message(msg);

or  

let mqtt_message = new Paho.MQTT.Message();
mqtt_message.payloadString = msg;

**Comment by icanos** [comment] 2016-10-06 07:26
Hi,

I've only used the ng2-mqtt to receive information and haven't tested the sending yet. Thanks for doing that :-)

I've updated the Message class with a constructor that takes the payload as an argument, could you please try the latest commit?

**Comment by saulofr** [comment] 2016-10-06 13:54
:/ Did not work . I try to send payload direct in send('topic','payload',...) and return this "wireMessage is not defined".
I try change to send(message: Message) and return the same error.

**Comment by icanos** [comment] 2016-10-11 06:58
I have added the missing WireMessage class to the export. Could you please test it again? I haven't had time to test the code yet.

Thanks!

**Comment by saulofr** [comment] 2016-10-11 22:07
Same error...

I tried:

```
    export class WireMessage {
        constructor(type: number, options: Object);
        ...
```

and nothing... :/

"ReferenceError: wireMessage is not defined
    at ClientImpl.Paho.MQTT.ClientImpl.send (http://localhost:8100/build/main.js:80318:15)
    at Client.send (http://localhost:8100/build/main.js:81340:12)
    at Object.onSuccess (http://localhost:8100/build/main.js:83065:39)
    at ClientImpl.Paho.MQTT.ClientImpl._handleMessage (http://localhost:8100/build/main.js:80642:26)
    at ClientImpl.Paho.MQTT.ClientImpl._on_socket_message (http://localhost:8100/build/main.js:80551:12)
    at WebSocket.<anonymous> (http://localhost:8100/build/main.js:79557:13)
    at WebSocket.n [as _onmessage](http://localhost:8100/build/polyfills.js:2:31845)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:14029)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:7166:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:13965)"

**Comment by saulofr** [comment] 2016-12-07 11:36
+1

**Comment by AinoL** [comment] 2016-12-12 12:23
Having the same issue so please let us know if you have any solutions.

**Comment by saulofr** [comment] 2016-12-15 13:19
Hi, I used https://www.npmjs.com/package/@types/mqtt with npm install mqtt

**Comment by tk-za** [comment] 2016-12-15 13:54
The issue is that the Message constructor in mqttws31.d.ts is missing.
Simple fix is to change it to something like
```javascript
export class Message {
    constructor(payload: any);
    payloadString: string;
    payloadBytes: Array<any>;
    destinationName: string;
    qos: number;
    retained: boolean;
    duplicate: boolean;
}
```

**Comment by icanos** [comment] 2016-12-15 19:25
Thank you, updated the Message class with the missing constructor.

**Comment by icanos** [comment] 2016-12-15 19:25
Closed it a little too fast, should test it out first :)

**Comment by piux** [comment] 2017-06-15 16:35
Greetings, i dont know if this issue is resolved, but im using mosca with websockets and this with ionic 3. 

with this example i have sucessfully send a message.

https://www.sakib.ninja/angular2-with-mqtt/

```

import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams , LoadingController, ToastController } from 'ionic-angular';
import { HomePage } from '../home/home';
import * as io from 'socket.io-client';
import {Platform} from 'ionic-angular';

import {Paho} from 'ng2-mqtt/mqttws31';
/**
 * Generated class for the AccesosPage page.
 *
 * See http://ionicframework.com/docs/components/#navigation for more info
 * on Ionic pages and navigation.
 */
@IonicPage()
@Component({
  selector: 'page-accesos',
  templateUrl: 'accesos.html',
})
export class AccesosPage {
  private _client: Paho.MQTT.Client;
  
   loading: any;

  socket:any
  chat_input:string;
  chats = [];

  constructor(
      public platform: Platform,
      public navCtrl: NavController,
      public navParams: NavParams ,
      public loadingCtrl: LoadingController, 
      private toastCtrl: ToastController) { 

 this._client = new Paho.MQTT.Client("192.168.0.22", 3000, "/path", "IonicClient");
    
    this._client.onConnectionLost = (responseObject: Object) => {
      console.log('Connection lost.');
    };
    
    this._client.onMessageArrived = (message: Paho.MQTT.Message) => {
      console.log('Message arrived.');
    };

    this._client.connect({ onSuccess: this.onConnected.bind(this) });      
    
            this.socket = io('http://localhost:9090');
            this.socket.on('TEST', (msg) => {
            console.log("message", msg);
            this.chats.push(msg);
        });
  }

  
  private onConnected():void {
    console.log('Connected to broker.');
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad AccesosPage');
  }
//this is how you send a message using mosca with websockets enabled
  sendMessage() {
    let packet = new Paho.MQTT.Message("Mi nuevo mensaje");
    packet.destinationName = "/inTopic";
    this._client.send(packet);
  }      
      //ignore this is using websockets
 send(msg) {
        if(msg != ''){
            this.socket.emit('message', msg);
            console.log(this._client);
        }
        this.chat_input = '';
    }

    return(){
        this.navCtrl.setRoot(HomePage);  
    }


}

```
Html Side
```
<!--
  Generated template for the AccesosPage page.

  See http://ionicframework.com/docs/components/#navigation for more info on
  Ionic pages and navigation.
-->
<ion-header>

  <ion-navbar>
    <ion-title>Accesos</ion-title>
  </ion-navbar>

</ion-header>


<ion-content padding>
  <h2>Dispositivos:</h2>
  <button ion-button block clear (click)="sendMessage('test')">
    sendMessage 
  </button> 
    <button ion-button block clear (click)="return()">
    Regresar
  </button>
    
   

</ion-content>


```

**Comment by saulofr** [comment] 2017-06-19 18:21
I'm using today "types/mqtt": "0.0.34" and "mqtt": "1.14.1"

**Closed as completed** 2019-03-25 14:28 UTC
